### ISSUE TITLE
rules_foreign_cc CI broken due to obsolete gmp dependency

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_foreign_cc#452] opened 2021-01-06 00:02 UTC
buildkite link: https://buildkite.com/bazel/rules-foreign-cc/builds/1240#8f6823c9-278e-4196-9ec8-44f3ed42dabb

```
(00:18:00) ERROR: /workdir/examples/configure_mpc/BUILD:3:15: //configure_mpc:gmp depends on @gmp//:all in repository @gmp which failed to fetch. no such package '@gmp//': java.io.IOException: Error downloading [https://mirror.bazel.build/gmplib.org/download/gmp/gmp-6.2.0.tar.gz, https://gmplib.org/download/gmp/gmp-6.2.0.tar.gz] to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/90e2e9b2d72fa9b00c19ff0535bb31ae/external/gmp/temp15082800512242903832/gmp-6.2.0.tar.gz: GET returned 404 Not Found
```

Neither the gmplib.org link or the bazel mirror are currently valid (both return 404).

**Comment by Wyverald** [comment] 2021-01-18 15:28
/poke this is still failing at HEAD: https://buildkite.com/bazel/rules-foreign-cc/builds/1272#b38feb22-aa2d-4801-913e-463d32993920

**Comment by whs-dot-hk** [comment] 2021-01-18 22:46
Hi, there is no `https://gmplib.org/download/gmp/gmp-6.2.0.tar.gz` but `https://gmplib.org/download/gmp/gmp-6.2.0.tar.xz`

Maybe, change `gz` to `xz`?

And there is a newer version `6.2.1` at `https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz`

**Comment by UebelAndre** [comment] 2021-01-22 02:41
@c-parsons I have a fix for this in https://github.com/bazelbuild/rules_foreign_cc/pull/453 I'd super appreciate getting a review for that change 🙏

**Comment by UebelAndre** [comment] 2021-01-22 14:00
This was recently fixed by @philwo (thank you!). PRs that are still showing failed builds should be able to fix that by amending a commit `git commit --amend --date=now` or rebasing (assuming the failure is caused by this issue).

**Closed by UebelAndre** 2021-01-22 14:00 UTC
