### ISSUE TITLE
New sandboxing feature (#479) is a reason for a failing apache_httpd example 

### ISSUE THREAD

**Issue by slsyy** [bazelbuild/rules_foreign_cc#502] opened 2021-02-10 16:40 UTC
```
bazel clean --expunge && bazel test  :apr_util --spawn_strategy=standalone
```
build apr_util library, where
```
bazel clean --expunge && bazel test  :apr
```

is failing because some build files from `apr` target are not visible by `apr_util` target

```
/bin/sh: /home/s/.cache/bazel/_bazel_s/1492138344810320fedb1deffadbaf6a/sandbox/linux-sandbox/1/execroot/rules_foreign_cc_tests/bazel-out/k8-fastbuild/bin/apache_httpd/apr.build_tmpdir/apr/build-1/libtool: No such file or directory
```
which is great, because we have found unspecified dependency.

Is there any way to modify `apr` rule, so it will export these files to `apr_util` target?

**Comment by UebelAndre** [comment] 2021-02-10 18:37
Would [configure_make.binaries](https://github.com/bazelbuild/rules_foreign_cc/tree/master/docs#configure_make-binaries) help?

**Comment by jsharpe** [comment] 2021-02-11 20:43
There are a few issues here:

1. We're not building all the examples in CI and so some of them are failing to build
2. Reverting #479 doesn't fix this for me (at least on Intel macOS BigSur)
3. Is there a reason you're having to use `--spawn_strategy=standalone` for building `//apache_httpd:apr_util`?
4. I think the error might be slightly misleading - I think the issue is that the apr build requires `configure_in_place = 1` to be set so that `libtool` is generated in the source tree.

**Comment by whs-dot-hk** [comment] 2021-02-16 13:12
Hi, @slsyy Try

```starlark
http_archive(
   name = "rules_foreign_cc",
   strip_prefix = "whs_rules_foreign_cc-master",
   url = "https://github.com/whs-dot-hk/whs_rules_foreign_cc/archive/master.zip",
)
```
It should work...  (they keep breaking this repo in turns... spam merging...)

**Comment by slsyy** [comment] 2021-02-23 12:43
I found the root cause:

```bash
$ grep -r 'linux-sandbox' | grep -v 'Configure.log' 
bin/apache_httpd/copy_apr/apr/bin/apr-1-config:APR_SOURCE_DIR="/home/s/.cache/bazel/_bazel_s/574522e525178645dc30ffc4bcb601a7/sandbox/linux-sandbox/4/execroot/rules_foreign_cc_tests/external/apr"
bin/apache_httpd/copy_apr/apr/build-1/apr_rules.mk:apr_builddir=/home/s/.cache/bazel/_bazel_s/574522e525178645dc30ffc4bcb601a7/sandbox/linux-sandbox/4/execroot/rules_foreign_cc_tests/bazel-out/k8-fastbuild/bin/apache_httpd/apr.build_tmpdir/apr/build-1
bin/apache_httpd/copy_apr/apr/build-1/apr_rules.mk:apr_builders=/home/s/.cache/bazel/_bazel_s/574522e525178645dc30ffc4bcb601a7/sandbox/linux-sandbox/4/execroot/rules_foreign_cc_tests/bazel-out/k8-fastbuild/bin/apache_httpd/apr.build_tmpdir/apr/build-1
bin/apache_httpd/copy_apr/apr/build-1/apr_rules.mk:top_builddir=/home/s/.cache/bazel/_bazel_s/574522e525178645dc30ffc4bcb601a7/sandbox/linux-sandbox/4/execroot/rules_foreign_cc_tests/bazel-out/k8-fastbuild/bin/apache_httpd/apr.build_tmpdir/apr/build-1
```

`*.mk` files are not the target for `replace_in_files` function. Applying the patch:

```diff
-  find -L $1 -type f   \\( -name "*.pc" -or -name "*.la" -or -name "*-config" -or -name "*.cmake" \\)   -exec sed -i 's@'"$2"'@'"$3"'@g' {} ';'
+  find -L $1 -type f   \\( -name "*.pc" -or -name "*.la" -or -name "*-config" -or -name "*.mk" -or -name "*.cmake" \\)   -exec sed -i 's@'"$2"'@'"$3"'@g' {} ';'
```

fix the issue. 
`configure_in_place = True` will improve hygiene, because `APR_SOURCE_DIR`  will be set to the correct path, but in the case of building an `:apr_util` it is not a problem

Shall I post a PR?

**Comment by UebelAndre** [comment] 2021-02-23 13:12
Yeah, a PR would be lovely 😄 Good catch!

**Comment by UebelAndre** [comment] 2021-08-22 23:15
I forget the status of this issue but vaguely recall it being resolved?

**Comment by jsharpe** [comment] 2021-08-28 21:31
I think we can close this now - we have examples in third_party that are compiling apr / apr_util.

**Closed by jsharpe** 2021-08-28 21:31 UTC
