### ISSUE TITLE
Permit __DATE__, __TIME__, etc in foreign builds

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/rules_foreign_cc#239] opened 2019-03-29 18:42 UTC
I'm using `configure_make` with apache and get this error
```
<command-line>:0:10: error: 'redacted' undeclared here (not in a function); did you mean 'rename'?
/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/sandbox/linux-sandbox/5/execroot/apache_bazel_example/external/org_apache_httpd/server/buildmark.c:21:36: note: in expansion of macro '__DATE__'
 static const char server_built[] = __DATE__ " " __TIME__;
```
because of the options
```
-Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted"
```
Could those be disabled by default for these external builds?

**Comment by jwnimmer-tri** [comment] 2019-03-29 18:57
From the peanut gallery (not a maintainer): the problem seems to be that the double-quoting is being dropped.  A literal `"redacted" " " "redacted"` would have been just fine.  Shell escaping must be wrong somewhere?

**Comment by UlysseM** [comment] 2019-03-29 22:22
I doubt you'd ever want to allow these, as they would change build artifacts all the time, which prevent any kinds of caching that bazel relies on.

Try adding this:
``` configure_options = ["CFLAGS='-Dredacted=\"redacted\"'"],```

**Comment by rnburn** [comment] 2019-03-29 22:44
Yes, it seems as if the problem is that they're not escaped correctly.

I don't know that it's important for apache - but if they're going to be fixed, I would suggest at least setting them to valid expansions in case there's code that parses them.

**Comment by tonyboxes** [comment] 2019-06-26 05:24
I'm using `cmake_external` to compile rocksdb and get this error
```
note: in expansion of macro '__DATE__'
```
I don't find `configure_options` attrs from docs.
Could those be disabled by default for these external builds?

**Comment by adam-rocska** [comment] 2019-09-16 23:36
I ran into the very same error trying to compile php (yeah...) : 
In case someone would like to reproduce it : https://github.com/adam-rocska/rules_php

`/Users/rocskaadam/bin/bazel build --tool_tag=ijwb:IDEA:ultimate --curses=no --color=yes --progress_in_terminal_title=no -- //php:php`

And in my local user `.bazelrc` : 
```
common --javabase @bazel_tools//tools/jdk:absolute_javabase --define=ABSOLUTE_JAVABASE=/Users/rocskaadam/lib/jdk-12.0.2.jdk --sandbox_debug --verbose_failures 

test //... --test_output=errors
```

**Comment by guoqi** [comment] 2019-12-16 12:11
If i really need this macro, what could i do to disable bazel's replacement? I could bear some loss of performance, but i don't find some solutions so far.

**Comment by PalaceChan** [comment] 2020-01-13 23:31
How can this replacement of those macros be disabled? There are use cases which can bear the performance hit but require this

**Comment by ilanbiala** [comment] 2020-10-30 07:58
I'm also using `cmake_external()` and hitting this issue. Is there a workaround/fix when using this rule?

**Comment by itdaniher** [comment] 2020-11-04 04:20
@ilanbiala after a bemusing round of string-escape tetris, I have found a solution!

```env_vars = {"CFLAGS": "-Dredacted='\\\"redacted\\\"'"}, ```

The same would hold for CXXFLAGS.

**Comment by attilaolah** [comment] 2021-06-11 13:35
The real problem here appears to be that the quoting seems to be different in the CMake and Configure/Make versions.

Here is how `build_script.sh` looks for a `configure_make` project (Python in this example):

```sh
ARFLAGS="rcsD" ASFLAGS="-U_FORTIFY_SOURCE -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -fstack-protector -D__DATE__=\"redacted\" -D__TIME__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -Wno-builtin-macro-redefined -no-canonical-prefixes" CFLAGS="-U_FORTIFY_SOURCE -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -fstack-protector -D__DATE__=\"redacted\" -D__TIME__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -Wno-builtin-macro-redefined -no-canonical-prefixes -DDATE='\"redacted\"' -DTIME='\"redacted\"'" CXXFLAGS="-U_FORTIFY_SOURCE -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -fstack-protector -std=c++17 -D__DATE__=\"redacted\" -D__TIME__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -Wno-builtin-macro-redefined -no-canonical-prefixes" LDFLAGS="-B${EXT_BUILD_ROOT}/external/llvm/bin --ld-path=${EXT_BUILD_ROOT}/external/llvm/bin/ld.lld -Wl,-no-as-needed -Wl,-z,relro,-z,now -lstdc++ -lm -no-canonical-prefixes -L$EXT_BUILD_DEPS/ffi_lib/lib -L$EXT_BUILD_DEPS/mpdecimal_lib/lib -L$EXT_BUILD_DEPS/z_lib/lib -L$EXT_BUILD_DEPS/openssl_lib/lib" AR="/.${EXT_BUILD_ROOT}/external/llvm/bin/llvm-ar" CC="/.${EXT_BUILD_ROOT}/external/llvm/bin/clang" CXX="/.${EXT_BUILD_ROOT}/external/llvm/bin/clang" CPPFLAGS="-I$EXT_BUILD_DEPS/ffi_lib/include -I$EXT_BUILD_DEPS/mpdecimal_lib/include -I$EXT_BUILD_DEPS/z_lib/include -I$EXT_BUILD_DEPS/openssl_lib/include" "$EXT_BUILD_ROOT/external/lib_python/configure" --prefix=$BUILD_TMPDIR/$INSTALL_PREFIX --disable-shared --with-openssl="${EXT_BUILD_DEPS}/openssl_lib" --with-system-libmpdec
```

While `cmake()` puts these into a `crosstool_bazel.cmake` script, which has a crazy number of escaping going on:

```
cat > crosstool_bazel.cmake << EOF
set(CMAKE_AR "/.${EXT_BUILD_ROOT}/external/llvm/bin/llvm-ar" CACHE FILEPATH "Archiver")
set(CMAKE_ASM_FLAGS_INIT "-U_FORTIFY_SOURCE -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -fstack-protector -D__DATE__='\\"\\\\\\"redacted\\"\\\\\\"' -D__TIME__='\\"\\\\\\"redacted\\"\\\\\\"' -D__TIMESTAMP__='\\"\\\\\\"redacted\\"\\\\\\"' -Wno-builtin-macro-redefined -no-canonical-prefixes")
set(CMAKE_CXX_COMPILER "/.${EXT_BUILD_ROOT}/external/llvm/bin/clang")
set(CMAKE_CXX_FLAGS_INIT "-U_FORTIFY_SOURCE -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -fstack-protector -std=c++17 -D__DATE__='\\"\\\\\\"redacted\\"\\\\\\"' -D__TIME__='\\"\\\\\\"redacted\\"\\\\\\"' -D__TIMESTAMP__='\\"\\\\\\"redacted\\"\\\\\\"' -Wno-builtin-macro-redefined -no-canonical-prefixes")
set(CMAKE_C_COMPILER "/.${EXT_BUILD_ROOT}/external/llvm/bin/clang")
set(CMAKE_C_FLAGS_INIT "-U_FORTIFY_SOURCE -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -fstack-protector -D__DATE__='\\"\\\\\\"redacted\\"\\\\\\"' -D__TIME__='\\"\\\\\\"redacted\\"\\\\\\"' -D__TIMESTAMP__='\\"\\\\\\"redacted\\"\\\\\\"' -Wno-builtin-macro-redefined -no-canonical-prefixes")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-B${EXT_BUILD_ROOT}/external/llvm/bin --ld-path=${EXT_BUILD_ROOT}/external/llvm/bin/ld.lld -Wl,-no-as-needed -Wl,-z,relro,-z,now -lstdc++ -lm -no-canonical-prefixes")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-shared -B${EXT_BUILD_ROOT}/external/llvm/bin --ld-path=${EXT_BUILD_ROOT}/external/llvm/bin/ld.lld -Wl,-no-as-needed -Wl,-z,relro,-z,now -lstdc++ -lm -no-canonical-prefixes")
EOF
```

Note the defines: `-D__DATE__='\\"\\\\\\"redacted\\"\\\\\\"'`. Something is clearly not right here, but I'm not sure where all these quotes are coming from.

**Comment by attilaolah** [comment] 2021-06-11 13:41
One workaround I found was to have `r"-D__DATE__=\"redacted\""` in the crosstool config, but then for Python also pass in `configure_env_vars = {"CFLAGS": r"""-DDATE='\"redacted\"' -DTIME='\"redacted\"'"""}`. This way even though `__DATE__` will not have the right escaping, Python will default to use `DATE` (and `TIME`) instead and just ignore `__DATE__` and `__TIME__`).

This works until the quoting can be mode more consistent.

---

A good example that uses `cmake()` and the timestamp macros is Exiv2, e.g. here: https://github.com/attilaolah/wasm/blob/main/lib/exiv2/BUILD.bazel

**Comment by jsharpe** [comment] 2021-08-28 21:44
Hopefully the quoting is correct now for CMake based builds. The quotes `-D__DATE__='\\"\\\\\\"redacted\\"\\\\\\"'.` that @attilaolah observed was indeed incorrect.

Unfortunately for `configure` style builds there isn't one set of quoting that works everywhere 😭 This is because some configure scripts aren't autotools based scripts and actually are written in other languages e.g. perl or sh and these handle the number of required escapes differently.

For those asking about disabling this - these redactions are configured as part of the cc_toolchain; if you want to turn it off you need to define your own toolchain to do this. If you need help in doing so I'd suggest that you ask on the bazel-discuss mailing list or in the bazel slack.

**Comment by attilaolah** [comment] 2021-12-05 11:15
For anyone reading the previous comment, here is a quick link to how one might enable/disable these in the `unfiltered_compile_flags` option: https://github.com/attilaolah/wasm/blob/b45df456d0f8b1e4ef414282f2b7848b2b89b55b/toolchains/cc/clang.bzl#L129-L141

**Comment by jheaff1** [comment] 2022-06-04 08:48
I submitted a PR bazelbuild/bazel#14735 to be able to remove all default flags from the built-in cc toolchains.

I submitted it 4 months ago and it still hasn’t been reviewed yet 😔

**Comment by jvolkman** [comment] 2023-01-08 14:15
@jheaff1 FYI looks like your upstream PR was merged.

**Comment by jheaff1** [comment] 2023-01-08 19:28
Yep glad to see it’s in Bazel 6.0!

**Comment by jsharpe** [comment] 2023-02-28 23:21
Given https://github.com/bazelbuild/bazel/pull/14735 is merged and there's not a lot we can do about the quoting situation as different build scripts require different styles of quoting, I'm going to close this now.

**Closed by jsharpe** 2023-02-28 23:21 UTC
Labels: Can Close?

**Comment by carlosgalvezp** [comment] 2023-03-08 18:54
One problem of using 'configure_options' like this is that CFLAGS are being redefined, overriding the toolchain flags entirely. Are there less invasive ways to do it?

**Comment by attilaolah** [comment] 2023-09-18 22:42
Another library that seems to break due to the quoting here is gmp, which generates a `gmp.h` that expects no quotes in `CFLAGS` :(

```
#define __GMP_CFLAGS "-U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted""
```

**Comment by snakethatlovesstaticlibs** [comment] 2025-03-26 22:04
I just found out about `SOURCE_DATE_EPOCH` (https://reproducible-builds.org/docs/source-date-epoch/) Would it make sense to support that instead of overriding `__TIME__` and friends?
