### ISSUE TITLE
ToolchainResolution on mac-aarch64

### ISSUE THREAD

**Issue by alexey-pelykh** [bazelbuild/rules_foreign_cc#1216] opened 2024-06-16 12:55 UTC
```
$  bazel build //:pcre2  --toolchain_resolution_debug='@@rules_foreign_cc~//toolchains:ninja_toolchain'
```

produces:

```
INFO: ToolchainResolution: Performing resolution of @@rules_foreign_cc~//toolchains:ninja_toolchain for target platform @@local_config_platform//:host
      ToolchainResolution:   Toolchain @@rules_foreign_cc~~tools~ninja_1.11.1_linux//:ninja_tool is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@local_config_platform//:host; mismatching values: x86_64, linux
      ToolchainResolution:   Toolchain @@rules_foreign_cc~~tools~ninja_1.11.1_mac//:ninja_tool is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@local_config_platform//:host; mismatching values: x86_64
      ToolchainResolution:   Toolchain @@rules_foreign_cc~~tools~ninja_1.11.1_win//:ninja_tool is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@local_config_platform//:host; mismatching values: x86_64, windows
      ToolchainResolution: No @@rules_foreign_cc~//toolchains:ninja_toolchain toolchain found for target platform @@local_config_platform//:host.
```

```
$ bazel --version
bazel 7.1.2-homebrew
```

```
$ cat MODULE.bazel
module(
    name = "test",
    version = "0.1",
)

http_archive = use_repo_rule(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "pcre2",
    urls = ["https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.44/pcre2-10.44.tar.bz2"],
    strip_prefix = "pcre2-10.44",
)

bazel_dep(
    name = "rules_foreign_cc",
    version = "0.10.1",
)
```

```
$ cat BUILD.bazel
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

cmake(
    name = "pcre2",
    lib_source = "@pcre2//:all",
)
```

**Comment by jsharpe** [comment] 2024-06-17 08:43
Duplicate of #1035

**Closed by jsharpe** 2024-06-17 08:43 UTC
